"""Add Stage 8 fields to ProcessedSignal

Revision ID: 305857878a78
Revises: a79fd3f8f2cd
Create Date: 2026-08-09 21:31:25.824963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '305857878a78'
down_revision: Union[str, Sequence[str], None] = 'a79fd3f8f2cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processed_signals', sa.Column('signal_quality', sa.String(length=50), nullable=True))
    op.add_column('processed_signals', sa.Column('source_metadata', sa.JSON(), nullable=True))
    op.add_column('processed_signals', sa.Column('embedding_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processed_signals', 'embedding_metadata')
    op.drop_column('processed_signals', 'source_metadata')
    op.drop_column('processed_signals', 'signal_quality')
    # ### end Alembic commands ###
