"""Add trend intelligence models

Revision ID: 4120527924f1
Revises: dae2d3caded1
Create Date: 2026-08-10 12:58:36.463863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4120527924f1'
down_revision: Union[str, Sequence[str], None] = 'dae2d3caded1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trend_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=100), nullable=True),
    sa.Column('cluster_run_id', sa.Integer(), nullable=False),
    sa.Column('algorithm_version', sa.String(length=50), nullable=True),
    sa.Column('scoring_version', sa.String(length=50), nullable=True),
    sa.Column('corpus_size', sa.Integer(), nullable=True),
    sa.Column('trend_count', sa.Integer(), nullable=True),
    sa.Column('configuration_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_run_id'], ['cluster_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trend_runs_id'), 'trend_runs', ['id'], unique=False)
    op.create_index(op.f('ix_trend_runs_run_id'), 'trend_runs', ['run_id'], unique=True)
    op.create_table('trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trend_run_id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('label_confidence', sa.String(length=50), nullable=True),
    sa.Column('trend_score', sa.Float(), nullable=True),
    sa.Column('trend_strength', sa.String(length=50), nullable=True),
    sa.Column('trend_confidence', sa.String(length=50), nullable=True),
    sa.Column('cluster_size', sa.Integer(), nullable=True),
    sa.Column('embedding_cohesion', sa.Float(), nullable=True),
    sa.Column('semantic_quality', sa.String(length=50), nullable=True),
    sa.Column('corpus_support', sa.Float(), nullable=True),
    sa.Column('source_diversity', sa.Float(), nullable=True),
    sa.Column('recency_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.ForeignKeyConstraint(['trend_run_id'], ['trend_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trends_id'), 'trends', ['id'], unique=False)
    op.create_index(op.f('ix_trends_trend_run_id'), 'trends', ['trend_run_id'], unique=False)
    op.create_table('trend_representatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trend_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['instagram_posts.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['processed_signals.id'], ),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trend_representatives_id'), 'trend_representatives', ['id'], unique=False)
    op.create_index(op.f('ix_trend_representatives_trend_id'), 'trend_representatives', ['trend_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trend_representatives_trend_id'), table_name='trend_representatives')
    op.drop_index(op.f('ix_trend_representatives_id'), table_name='trend_representatives')
    op.drop_table('trend_representatives')
    op.drop_index(op.f('ix_trends_trend_run_id'), table_name='trends')
    op.drop_index(op.f('ix_trends_id'), table_name='trends')
    op.drop_table('trends')
    op.drop_index(op.f('ix_trend_runs_run_id'), table_name='trend_runs')
    op.drop_index(op.f('ix_trend_runs_id'), table_name='trend_runs')
    op.drop_table('trend_runs')
    # ### end Alembic commands ###
