"""add_content_sources_and_media_fields

Revision ID: a79fd3f8f2cd
Revises: d4131c3e528b
Create Date: 2026-08-08 16:41:08.521180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a79fd3f8f2cd'
down_revision: Union[str, Sequence[str], None] = 'd4131c3e528b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=True),
    sa.Column('processor_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['instagram_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_sources_id'), 'content_sources', ['id'], unique=False)
    op.create_index(op.f('ix_content_sources_post_id'), 'content_sources', ['post_id'], unique=False)
    op.add_column('instagram_posts', sa.Column('media_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instagram_posts', 'media_type')
    op.drop_index(op.f('ix_content_sources_post_id'), table_name='content_sources')
    op.drop_index(op.f('ix_content_sources_id'), table_name='content_sources')
    op.drop_table('content_sources')
    # ### end Alembic commands ###
