"""stage_4_observability

Revision ID: cea889cb757d
Revises: f0eacef576cd
Create Date: 2026-08-08 15:04:53.657027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cea889cb757d'
down_revision: Union[str, Sequence[str], None] = 'f0eacef576cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_page_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_internal_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('posts_discovered', sa.Integer(), nullable=True),
    sa.Column('new_posts', sa.Integer(), nullable=True),
    sa.Column('existing_posts', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['instagram_pages.id'], ),
    sa.ForeignKeyConstraint(['run_internal_id'], ['collection_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_page_results_id'), 'collection_page_results', ['id'], unique=False)
    op.create_index(op.f('ix_collection_page_results_page_id'), 'collection_page_results', ['page_id'], unique=False)
    op.create_index(op.f('ix_collection_page_results_run_internal_id'), 'collection_page_results', ['run_internal_id'], unique=False)
    op.create_index(op.f('ix_collection_page_results_status'), 'collection_page_results', ['status'], unique=False)
    op.add_column('collection_runs', sa.Column('run_id', sa.String(length=100), nullable=False))
    op.add_column('collection_runs', sa.Column('session_state', sa.String(length=50), nullable=True))
    op.add_column('collection_runs', sa.Column('unique_posts', sa.Integer(), nullable=True))
    op.add_column('collection_runs', sa.Column('parser_errors', sa.Integer(), nullable=True))
    op.add_column('collection_runs', sa.Column('navigation_errors', sa.Integer(), nullable=True))
    op.add_column('collection_runs', sa.Column('timeout_errors', sa.Integer(), nullable=True))
    op.add_column('collection_runs', sa.Column('login_wall_events', sa.Integer(), nullable=True))
    op.add_column('collection_runs', sa.Column('challenge_events', sa.Integer(), nullable=True))
    op.add_column('collection_runs', sa.Column('access_denied_events', sa.Integer(), nullable=True))
    op.add_column('collection_runs', sa.Column('rate_limit_indicators', sa.Integer(), nullable=True))
    op.add_column('collection_runs', sa.Column('duration_ms', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_collection_runs_run_id'), 'collection_runs', ['run_id'], unique=True)
    op.create_index(op.f('ix_collection_runs_status'), 'collection_runs', ['status'], unique=False)
    op.drop_column('collection_runs', 'error_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection_runs', sa.Column('error_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_collection_runs_status'), table_name='collection_runs')
    op.drop_index(op.f('ix_collection_runs_run_id'), table_name='collection_runs')
    op.drop_column('collection_runs', 'duration_ms')
    op.drop_column('collection_runs', 'rate_limit_indicators')
    op.drop_column('collection_runs', 'access_denied_events')
    op.drop_column('collection_runs', 'challenge_events')
    op.drop_column('collection_runs', 'login_wall_events')
    op.drop_column('collection_runs', 'timeout_errors')
    op.drop_column('collection_runs', 'navigation_errors')
    op.drop_column('collection_runs', 'parser_errors')
    op.drop_column('collection_runs', 'unique_posts')
    op.drop_column('collection_runs', 'session_state')
    op.drop_column('collection_runs', 'run_id')
    op.drop_index(op.f('ix_collection_page_results_status'), table_name='collection_page_results')
    op.drop_index(op.f('ix_collection_page_results_run_internal_id'), table_name='collection_page_results')
    op.drop_index(op.f('ix_collection_page_results_page_id'), table_name='collection_page_results')
    op.drop_index(op.f('ix_collection_page_results_id'), table_name='collection_page_results')
    op.drop_table('collection_page_results')
    # ### end Alembic commands ###
