"""Add vertical scope to sources

Revision ID: cef400af3eee
Revises: e01e43a681cd
Create Date: 2026-08-10 15:14:32.358861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cef400af3eee'
down_revision: Union[str, Sequence[str], None] = 'e01e43a681cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection_runs', sa.Column('vertical_scope', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_collection_runs_vertical_scope'), 'collection_runs', ['vertical_scope'], unique=False)
    op.add_column('instagram_pages', sa.Column('vertical', sa.String(length=50), nullable=False, server_default='GENERAL'))
    op.add_column('instagram_pages', sa.Column('priority', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_instagram_pages_vertical'), 'instagram_pages', ['vertical'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instagram_pages_vertical'), table_name='instagram_pages')
    op.drop_column('instagram_pages', 'priority')
    op.drop_column('instagram_pages', 'vertical')
    op.drop_index(op.f('ix_collection_runs_vertical_scope'), table_name='collection_runs')
    op.drop_column('collection_runs', 'vertical_scope')
    # ### end Alembic commands ###
