"""add_stage5_processor_fields

Revision ID: d4131c3e528b
Revises: cea889cb757d
Create Date: 2026-08-08 15:28:59.309385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4131c3e528b'
down_revision: Union[str, Sequence[str], None] = 'cea889cb757d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processed_signals', sa.Column('extracted_hashtags', sa.JSON(), nullable=True))
    op.add_column('processed_signals', sa.Column('processor_version', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processed_signals', 'processor_version')
    op.drop_column('processed_signals', 'extracted_hashtags')
    # ### end Alembic commands ###
