"""Add hdbscan phase 12 fields

Revision ID: dae2d3caded1
Revises: 305857878a78
Create Date: 2026-08-10 12:50:31.810074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dae2d3caded1'
down_revision: Union[str, Sequence[str], None] = '305857878a78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster_runs', sa.Column('run_id', sa.String(length=100), nullable=True))
    op.add_column('cluster_runs', sa.Column('algorithm', sa.String(length=50), nullable=True))
    op.add_column('cluster_runs', sa.Column('embedding_dimension', sa.Integer(), nullable=True))
    op.add_column('cluster_runs', sa.Column('metric', sa.String(length=50), nullable=True))
    op.add_column('cluster_runs', sa.Column('corpus_size', sa.Integer(), nullable=True))
    op.add_column('cluster_runs', sa.Column('cluster_count', sa.Integer(), nullable=True))
    op.add_column('cluster_runs', sa.Column('noise_count', sa.Integer(), nullable=True))
    op.add_column('cluster_runs', sa.Column('configuration_hash', sa.String(length=255), nullable=True))
    op.drop_index(op.f('ix_cluster_runs_run_name'), table_name='cluster_runs')
    op.create_index(op.f('ix_cluster_runs_run_id'), 'cluster_runs', ['run_id'], unique=True)
    op.add_column('clusters', sa.Column('cluster_id', sa.String(length=100), nullable=True))
    op.add_column('clusters', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('clusters', sa.Column('representative_signal_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_clusters_cluster_id'), 'clusters', ['cluster_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clusters_cluster_id'), table_name='clusters')
    op.drop_column('clusters', 'representative_signal_id')
    op.drop_column('clusters', 'status')
    op.drop_column('clusters', 'cluster_id')
    op.drop_index(op.f('ix_cluster_runs_run_id'), table_name='cluster_runs')
    op.create_index(op.f('ix_cluster_runs_run_name'), 'cluster_runs', ['run_name'], unique=True)
    op.drop_column('cluster_runs', 'configuration_hash')
    op.drop_column('cluster_runs', 'noise_count')
    op.drop_column('cluster_runs', 'cluster_count')
    op.drop_column('cluster_runs', 'corpus_size')
    op.drop_column('cluster_runs', 'metric')
    op.drop_column('cluster_runs', 'embedding_dimension')
    op.drop_column('cluster_runs', 'algorithm')
    op.drop_column('cluster_runs', 'run_id')
    # ### end Alembic commands ###
