"""Add stage 10 trend analytics fields

Revision ID: e01e43a681cd
Revises: 4120527924f1
Create Date: 2026-08-10 13:08:33.916772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e01e43a681cd'
down_revision: Union[str, Sequence[str], None] = '4120527924f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trend_runs', sa.Column('metrics_availability', sa.JSON(), nullable=True))
    op.add_column('trend_runs', sa.Column('analytics_metadata', sa.JSON(), nullable=True))
    op.add_column('trend_runs', sa.Column('snapshot_started_at', sa.DateTime(), nullable=True))
    op.add_column('trend_runs', sa.Column('snapshot_finished_at', sa.DateTime(), nullable=True))
    op.add_column('trend_runs', sa.Column('snapshot_date', sa.String(length=50), nullable=True))
    op.add_column('trend_runs', sa.Column('snapshot_period', sa.String(length=50), nullable=True))
    op.add_column('trends', sa.Column('label_quality', sa.String(length=50), nullable=True))
    op.add_column('trends', sa.Column('label_quality_reason', sa.String(length=255), nullable=True))
    op.add_column('trends', sa.Column('trend_status', sa.String(length=50), nullable=True))
    op.add_column('trends', sa.Column('evidence_strength', sa.String(length=50), nullable=True))
    op.add_column('trends', sa.Column('platform_diversity', sa.Float(), nullable=True))
    op.add_column('trends', sa.Column('account_concentration', sa.Float(), nullable=True))
    op.add_column('trends', sa.Column('independent_source_strength', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trends', 'independent_source_strength')
    op.drop_column('trends', 'account_concentration')
    op.drop_column('trends', 'platform_diversity')
    op.drop_column('trends', 'evidence_strength')
    op.drop_column('trends', 'trend_status')
    op.drop_column('trends', 'label_quality_reason')
    op.drop_column('trends', 'label_quality')
    op.drop_column('trend_runs', 'snapshot_period')
    op.drop_column('trend_runs', 'snapshot_date')
    op.drop_column('trend_runs', 'snapshot_finished_at')
    op.drop_column('trend_runs', 'snapshot_started_at')
    op.drop_column('trend_runs', 'analytics_metadata')
    op.drop_column('trend_runs', 'metrics_availability')
    # ### end Alembic commands ###
