"""Initial

Revision ID: f0eacef576cd
Revises: 
Create Date: 2026-08-08 12:33:04.036567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'f0eacef576cd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_label', sa.String(length=255), nullable=True),
    sa.Column('signal_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clusters_id'), 'clusters', ['id'], unique=False)
    op.create_table('collection_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('pages_attempted', sa.Integer(), nullable=True),
    sa.Column('pages_successful', sa.Integer(), nullable=True),
    sa.Column('pages_failed', sa.Integer(), nullable=True),
    sa.Column('posts_discovered', sa.Integer(), nullable=True),
    sa.Column('new_posts', sa.Integer(), nullable=True),
    sa.Column('existing_posts', sa.Integer(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_runs_id'), 'collection_runs', ['id'], unique=False)
    op.create_index(op.f('ix_collection_runs_started_at'), 'collection_runs', ['started_at'], unique=False)
    op.create_table('instagram_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('profile_url', sa.String(length=512), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('last_collected_at', sa.DateTime(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_post_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_pages_active'), 'instagram_pages', ['active'], unique=False)
    op.create_index(op.f('ix_instagram_pages_id'), 'instagram_pages', ['id'], unique=False)
    op.create_index(op.f('ix_instagram_pages_username'), 'instagram_pages', ['username'], unique=True)
    op.create_table('collection_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['instagram_pages.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['collection_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_errors_id'), 'collection_errors', ['id'], unique=False)
    op.create_index(op.f('ix_collection_errors_run_id'), 'collection_errors', ['run_id'], unique=False)
    op.create_table('instagram_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('instagram_post_id', sa.String(length=100), nullable=False),
    sa.Column('post_url', sa.String(length=512), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('hashtags', sa.JSON(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('media_url', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['instagram_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_posts_id'), 'instagram_posts', ['id'], unique=False)
    op.create_index(op.f('ix_instagram_posts_instagram_post_id'), 'instagram_posts', ['instagram_post_id'], unique=True)
    op.create_index(op.f('ix_instagram_posts_page_id'), 'instagram_posts', ['page_id'], unique=False)
    op.create_index(op.f('ix_instagram_posts_published_at'), 'instagram_posts', ['published_at'], unique=False)
    op.create_table('processed_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('canonical_text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['instagram_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_signals_id'), 'processed_signals', ['id'], unique=False)
    op.create_index(op.f('ix_processed_signals_post_id'), 'processed_signals', ['post_id'], unique=False)
    op.create_index(op.f('ix_processed_signals_processing_status'), 'processed_signals', ['processing_status'], unique=False)
    op.create_table('cluster_members',
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['processed_signals.id'], ),
    sa.PrimaryKeyConstraint('cluster_id', 'signal_id')
    )
    op.create_index(op.f('ix_cluster_members_cluster_id'), 'cluster_members', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_cluster_members_signal_id'), 'cluster_members', ['signal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cluster_members_signal_id'), table_name='cluster_members')
    op.drop_index(op.f('ix_cluster_members_cluster_id'), table_name='cluster_members')
    op.drop_table('cluster_members')
    op.drop_index(op.f('ix_processed_signals_processing_status'), table_name='processed_signals')
    op.drop_index(op.f('ix_processed_signals_post_id'), table_name='processed_signals')
    op.drop_index(op.f('ix_processed_signals_id'), table_name='processed_signals')
    op.drop_table('processed_signals')
    op.drop_index(op.f('ix_instagram_posts_published_at'), table_name='instagram_posts')
    op.drop_index(op.f('ix_instagram_posts_page_id'), table_name='instagram_posts')
    op.drop_index(op.f('ix_instagram_posts_instagram_post_id'), table_name='instagram_posts')
    op.drop_index(op.f('ix_instagram_posts_id'), table_name='instagram_posts')
    op.drop_table('instagram_posts')
    op.drop_index(op.f('ix_collection_errors_run_id'), table_name='collection_errors')
    op.drop_index(op.f('ix_collection_errors_id'), table_name='collection_errors')
    op.drop_table('collection_errors')
    op.drop_index(op.f('ix_instagram_pages_username'), table_name='instagram_pages')
    op.drop_index(op.f('ix_instagram_pages_id'), table_name='instagram_pages')
    op.drop_index(op.f('ix_instagram_pages_active'), table_name='instagram_pages')
    op.drop_table('instagram_pages')
    op.drop_index(op.f('ix_collection_runs_started_at'), table_name='collection_runs')
    op.drop_index(op.f('ix_collection_runs_id'), table_name='collection_runs')
    op.drop_table('collection_runs')
    op.drop_index(op.f('ix_clusters_id'), table_name='clusters')
    op.drop_table('clusters')
    # ### end Alembic commands ###
